### ISSUE TITLE
Looking for a maintainer to take over in 2023

### ISSUE THREAD

**Issue by TomasVotruba** [danharrin/monorepo-split-github-action#43]
Hi everyone,

to be honest, I don't have time to maintain this package and keep it high quality.
If you find it useful and want to improve it to the bright future, let me know.

Tomas

**Comment by danharrin** [comment]
We use it extensively at @filamentphp, so if no-one else is going to maintain it, we will.

I have very limited knowledge of GitHub actions though, so maintenance will likely be keeping it stable rather than adding new features.

**Comment by TomasVotruba** [comment]
Thanks for quick answer. This sounds great :)

What account should I transfer it to?

**Comment by danharrin** [comment]
@danharrin please

**Comment by danharrin** [comment]
are you still maintaining monorepo-builder?

**Comment by TomasVotruba** [comment]
@danharrin Should be moved right now :)

Yeah, for time being the monorepo is quite used and I maintain it :+1:

**Comment by zepfietje** [comment]
Great work, guys. This issue can now be closed I suppose?
