### ISSUE TITLE
fatal: detected dubious ownership in repository at '/github/workspace'

### ISSUE THREAD

**Issue by hashstudiobackend** [danharrin/monorepo-split-github-action#46]
I am getting error while running 'symplify/monorepo-split-github-action@2.1'

![Screen Shot 2023-02-28 at 4 47 32 PM](https://user-images.githubusercontent.com/111043338/221889219-5a9fd2e7-d306-4458-8de2-09b436b626bb.png)

**Comment by richardhj** [comment]
See #36.
Use `danharrin/monorepo-split-github-action@v2.3.0`

**Comment by hashstudiobackend** [comment]
@richardhj Thanks a lot
